Add test for Update Certificate
plesk/api-php-lib pull request #124
Opened 2023-05-02 15:04 UTC by Stas-81

Added test for update certificate scenario:
1. create certificate
2. install certificate serverwide
3. update installed certificate

tests execution:
Certificate (PleskXTest\Certificate)
 ✔ Generate  392 ms
 ✔ Install  661 ms
 ✔ Update  768 ms
 ✔ Delete  434 ms

2023-05-03 10:42 UTC, Stas-81 commented on tests/CertificateTest.php
> +        $result = static::$client->certificate()->update($payLoad, $certificate->request, $certificate->privateKey);
add certificate update by new generated certificate

2023-05-03 10:44 UTC, Stas-81 commented on src/Api/Operator/Certificate.php
> +    public function update(array $properties, string $request, string $privateKey): bool
Add usage of public parts ("cert") in test

2023-05-04 11:34 UTC, xgin requested changes

2023-05-04 11:34 UTC, xgin commented on src/Api/Operator/Certificate.php
> +        if (gettype($request) == 'string') {
is_string

2023-05-04 11:34 UTC, xgin commented on src/Api/Operator/Certificate.php
> +        } elseif (gettype($request) == 'object') {
instanceof PleskX\Api\Struct\Certificate\Info

2023-05-04 11:34 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
> +            'cert' => $this->body ?? null,
change variable declaration `public ?string $body = null` and you don't have to check it

2023-05-04 11:34 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
> +            'cert' => $this->body ?? null,
let's rename body to publicKey

2023-05-04 11:34 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
> +            'cert' => $this->body ?? null,
what about 'ca' part?

2023-05-04 11:35 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    public function callApi(string $method, array $properties, $request, string $privateKey = null): bool
private

2023-05-04 11:35 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    public function install(array $properties, $request, string $privateKey = null): bool
rename $request to $certificate

2023-05-04 11:36 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    public function install(array $properties, $request, string $privateKey = null): bool
add doc blocks to declare typehinting

2023-05-04 11:37 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
> +        if (!is_array($input)) {
instanceof \SimpleXMLElement

2023-05-04 11:38 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    public function update(array $properties, $request, string $privateKey = null): bool
no need of $privateKey in update method

2023-05-04 11:39 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    public function install(array $properties, $request, string $privateKey = null): bool
`?string $privateKey` - because it is nullable. or just remove type here, because it is legacy.

2023-05-04 17:43 UTC, xgin requested changes

2023-05-04 17:43 UTC, xgin commented on src/Api/Operator/Certificate.php
> +     * @param ?string $privateKey
```suggestion
     * @param string|null $privateKey
```

2023-05-04 17:43 UTC, xgin commented on src/Api/Operator/Certificate.php
> +     * @param string | Struct\Info $certificate
```suggestion
     * @param string|Struct\Info $certificate
```

2023-05-04 17:43 UTC, xgin commented on src/Api/Operator/Certificate.php
> +     * @param string | Struct\Info $certificate
```suggestion
     * @param Struct\Info $certificate
```

2023-05-04 17:43 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
>      public string $request;
```suggestion
    public ?string $request = null;
```

2023-05-04 17:43 UTC, xgin commented on src/Api/Struct/Certificate/Info.php
>      public string $privateKey;
```suggestion
    public ?string $privateKey = null;
```

2023-05-04 18:07 UTC, xgin commented on src/Api/Operator/Certificate.php
> +    private function callApi(string $method, array $properties, $certificate, ?string $privateKey = null): bool
```suggestion
    private function callApi(string $method, array $properties, Struct\Info $certificate): bool
```

2023-05-04 18:08 UTC, xgin commented on src/Api/Operator/Certificate.php
> +        } elseif ($certificate instanceof \PleskX\Api\Struct\Certificate\Info) {
```suggestion
        } elseif ($certificate instanceof Struct\Info) {
```

2023-05-05 08:29 UTC, Stas-81 commented on src/Api/Operator/Certificate.php
> +        } elseif ($certificate instanceof \PleskX\Api\Struct\Certificate\Info) {
all issues fixed

2023-05-05 14:24 UTC, xgin approved these changes

2023-05-05 14:25 UTC, merged